---
title: "JJiang_HW4"
author: "Joe Jiang"
date: "November 29, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(ggplot2)
library(dplyr)
```

### Question 1, scape and reshape a table comprised of cast members of *Harry Potter Deathly Hallow 2*

```{r Scape a table from a website}
#scape the web for a table using rvest
url <- "https://www.imdb.com/title/tt1201607/fullcredits?ref_=tt_ql_1"
hpcast <- url %>%
	read_html() %>%
  html_nodes(xpath='//*[@id="fullcredits_content"]/table[3]') %>%
  html_table()
hpcast <- hpcast[[1]]
```
```{r  Clean up the table}
#delete the blank rows and columns
hpcast <- hpcast[2:157,c(2,4)]

#column/row names 
colnames(hpcast) <- c("actor", "Character")
rownames(hpcast) <- NULL

#remove the row 'Rest of cast listed alphabetically:' and carriage and other hidden characters
hpcast <- hpcast[hpcast$actor != 'Rest of cast listed alphabetically:',]
hpcast <- sapply(hpcast, function(x){gsub("(\\\\r|\\\\n|\\n|\\\\t|\\s)+", " ", x)}) #remove blank and carriage return, tabs ...
hpcast <- data.frame(hpcast,  stringsAsFactors = FALSE)

# simpler code if ignoring three actors with multiple-letter last names
firstname = sapply(strsplit(hpcast$actor, ' '), function(x) paste(x[1:length(x)-1], collapse = " "))
lastname = sapply(strsplit(hpcast$actor, ' '), function(x) x[length(x)])
hpcast$FirstName <- firstname
hpcast$LastName <- lastname
hpcast <- hpcast[, c(3,4,2)] #rearrange the columns 
knitr::kable(head(hpcast,10), format = "markdown")
```

### Question 2 scape and reshape a table from ESPN, then plot *FG%* of *San Antonio Spurs* players


```{r Scape the table containing the shooting stats of San Antonio Spurs from ESPN website}
#scape the espn website for a table
url <- "http://www.espn.com/nba/team/stats/_/name/sa/san-antonio-spurs"
spursShootingStats <- url %>%
	read_html() %>%
  html_table(fill = TRUE)
spursShootingStats <- spursShootingStats[[2]]

#clean up the table 
spursShootingStats <- spursShootingStats[2:16,]
rownames(spursShootingStats) <- NULL
colnames(spursShootingStats) = spursShootingStats[1, ] #set the first row as column names =
spursShootingStats <- spursShootingStats[-1, ] #delete the first row
knitr::kable(head(spursShootingStats), format = "markdown", row.names = FALSE)
```

```{r split the first column into player name and their position}
name = sapply(strsplit(spursShootingStats$PLAYER, ','), function(x) x[1]) #split the name
position = sapply(strsplit(spursShootingStats$PLAYER, ','), function(x) x[2]) #split the position
spursShootingStats$Name <- name
spursShootingStats$Position <- position
spursShootingStats <- spursShootingStats[, c(16, 17, 2:15)] #rearrange the columns 
knitr::kable(head(spursShootingStats), format = "markdown", row.names = FALSE)
```

```{r change datatypes }
sapply(spursShootingStats, class) #before convertion
spursShootingStats[, c(3:16 )] <- sapply(spursShootingStats[, c(3:16)], as.numeric)
sapply(spursShootingStats, class) #after conversion
```

```{r fig.cap = "Fig. 1 *Field goals percentage per game (FG%)* of San Antonio Spurs (data from http://www.espn.com/nba/team/stats/_/name/sa/san-antonio-spurs)", fig.align ="center", out.width = "75%"}
spursShootingStats%>%ggplot(aes(x = `Name`, y = `FG%`)) +
  geom_bar(stat = 'identity', color = "black", fill ='red') +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  xlab("San Antonio Spurs Players") +
  ylab("FG%") +
  ggtitle("Field Goals Percentage Per Game Of San Antonio Spurs Players")+
  theme(plot.title = element_text(hjust = 0.5))
```
 


